import os
import sqlite3
import psycopg
from psycopg import sql

SQLITE_DB = "hardware_inventory.db"
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set.")

print("Connecting to databases...")
sqlite_conn = sqlite3.connect(SQLITE_DB)
sqlite_conn.row_factory = sqlite3.Row

pg_conn = psycopg.connect(DATABASE_URL)
pg_conn.autocommit = False

try:
    pg_cur = pg_conn.cursor()
    sqlite_cur = sqlite_conn.cursor()

    # Clean slate: Drop existing tables
    for tbl in ["loans", "password_resets", "hardware", "users"]:
        pg_cur.execute(sql.SQL("DROP TABLE IF EXISTS {} CASCADE").format(sql.Identifier(tbl)))

    table_definitions = {
        "users": [
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT UNIQUE NOT NULL",
            "email TEXT NOT NULL DEFAULT 'user@campus.edu'",
            "password_hash TEXT NOT NULL",
            "role TEXT NOT NULL DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER'))",
            "login_attempts INTEGER NOT NULL DEFAULT 0",
            "is_locked INTEGER NOT NULL DEFAULT 0",
        ],
        "password_resets": [
            "request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "email TEXT NOT NULL",
            "password_hash TEXT",
            "status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))",
            "requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
            "reviewed_at TIMESTAMP",
        ],
        "hardware": [
            "item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "item_name TEXT NOT NULL",
            "category TEXT NOT NULL",
            "quantity INTEGER NOT NULL",
            "unit_price DOUBLE PRECISION NOT NULL",
            "status TEXT NOT NULL",
        ],
        "loans": [
            "loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            "username TEXT NOT NULL",
            "item_id BIGINT",  # Made nullable to tolerate legacy/test records
            "item_name TEXT",
            "quantity INTEGER NOT NULL DEFAULT 1",
            "status TEXT NOT NULL DEFAULT 'PENDING_BORROW'",
            "borrowed_at TIMESTAMP",
            "expected_return TIMESTAMP",
            "returned_at TIMESTAMP",
            "remarks TEXT",
        ],
    }

    # 1. Create tables in PostgreSQL
    for table_name, columns in table_definitions.items():
        column_sql = sql.SQL(", ").join(sql.SQL(col) for col in columns)
        create_sql = sql.SQL("CREATE TABLE {} ({})").format(sql.Identifier(table_name), column_sql)
        pg_cur.execute(create_sql)

    counts = {}
    # 2. Migrate rows
    for table_name in table_definitions.keys():
        sqlite_cur.execute(f"SELECT name FROM sqlite_master WHERE type='table' AND (name='{table_name}' OR name='password_reset_requests')")
        found_tbl = sqlite_cur.fetchone()
        if not found_tbl:
            counts[table_name] = 0
            continue

        src_table = found_tbl[0]
        sqlite_cur.execute(f"SELECT * FROM {src_table}")
        rows = sqlite_cur.fetchall()
        counts[table_name] = len(rows)

        if not rows:
            continue

        source_cols = [desc[0] for desc in sqlite_cur.description]
        
        insert_cols = []
        for col in source_cols:
            if col == "failed_attempts":
                insert_cols.append("login_attempts")
            elif col == "request_time":
                insert_cols.append("requested_at")
            elif col == "new_password_hash":
                insert_cols.append("password_hash")
            else:
                insert_cols.append(col)

        target_cols_declared = [c.split()[0].lower() for c in table_definitions[table_name]]
        valid_pairs = [(src, tgt) for src, tgt in zip(source_cols, insert_cols) if tgt.lower() in target_cols_declared]

        if not valid_pairs:
            continue

        use_src_cols, use_tgt_cols = zip(*valid_pairs)

        col_ids = sql.SQL(", ").join(sql.Identifier(c) for c in use_tgt_cols)
        placeholders = sql.SQL(", ").join(sql.Placeholder() for _ in use_tgt_cols)
        insert_sql = sql.SQL("INSERT INTO {} ({}) VALUES ({})").format(
            sql.Identifier(table_name), col_ids, placeholders
        )

        for row in rows:
            values = list(row[c] for c in use_src_cols)
            pg_cur.execute(insert_sql, values)

    # 3. Synchronize identity sequences
    sequence_columns = {
        "users": "id",
        "password_resets": "request_id",
        "hardware": "item_id",
        "loans": "loan_id",
    }

    for table_name, id_column in sequence_columns.items():
        sequence_sql = sql.SQL("SELECT setval(pg_get_serial_sequence({}, {}), COALESCE(MAX({}), 0), MAX({}) IS NOT NULL) FROM {}").format(
            sql.Literal(table_name),
            sql.Literal(id_column),
            sql.Identifier(id_column),
            sql.Identifier(id_column),
            sql.Identifier(table_name),
        )
        pg_cur.execute(sequence_sql)

    pg_conn.commit()
    print("Migration completed successfully.")
    print(f"  users:            {counts['users']}")
    print(f"  password_resets:  {counts['password_resets']}")
    print(f"  hardware:         {counts['hardware']}")
    print(f"  loans:             {counts['loans']}")

except Exception as e:
    pg_conn.rollback()
    print(f"Error during migration: {e}")
    raise e
finally:
    sqlite_conn.close()
    pg_conn.close()